export {
  OrcabotHero,
  ProblemSection,
  SolutionSection,
  HowItWorksSection,
  DifferencesSection,
  ReceiveSection,
  TestimonialSection,
  BeginnerSection,
  ExpectationsSection,
  WhoItIsForSection,
  OrcabotPricingSection,
  FaqSection,
  OrcabotCtaSection,
  DisclaimerSection,
} from './components/OrcabotSections';
